
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.44.2
    hooks:
      - id: ruff
        args: ["--fix"]

